
baseURL = "https://blog.peakbreaker.com" # The URL of your site.
languageCode = "en-us"
title = "peakBreaker" # Title of your site
theme = "zzo" # Name of Zzo theme folder in `themes/`.
enableRobotsTXT = true

defaultContentLanguage = "en" # Default language to use (if you setup multilingual)
defaultContentLanguageInSubdir = true # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.

summaryLength = 70 # The length of a post description on a list page.

copyright = "&copy;{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
paginate = 13 # Number of items per page in paginated lists.
rssLimit = 100

googleAnalytics = "UA-117207692-1"

ignoreFiles = [ ".*/venv/.*", ".*\\.ipynb", ".*\\.gz", ".*\\.bin", ".*\\.ipynb_checkpoints.*", ".*\\.zip", ".*\\.tsv"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true
  xHTML = true
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5


[outputs]
home = ["HTML", "RSS", "JSON", "WEBMANIFEST"]

[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[outputFormats.webmanifest]
name = "webmanifest"
baseName = "webmanifest"
mediaType = "application/manifest+json"
rel = "manifest"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

