
[[main]]
  identifier = "about"
  name = "about"
  url = "about/peakbreaker"
  weight = 1

[[main]]
  identifier = "contact"
  name = "contact"
  url = "contact"
  weight = 2

[[main]]
  identifier = "showcase"
  name =  '<span style="color:green;">showcase</span>'
  url = "showcase"
  weight = 3

[[main]]
  identifier = "microposts"
  name = '<span style="color:CornflowerBlue;">microposts</span>'
  url = "micropost"
  weight = 7

[[main]]
  identifier = "subscribe"
  name = '<span style="color:red;">subscribe</span>'
  url = "https://sub.peakbreaker.com/subscribe"
  weight = 10

# 
# [[main]]
  # identifier = "gallery"
  # name = "gallery"
  # url = "gallery"
  # weight = 3
    # 
# [[main]]
  # parent = "gallery"
  # name = "cartoon"
  # url = "gallery/cartoon"
# 
# [[main]]
  # parent = "gallery"
  # name = "photo"
  # url = "gallery/photo"

# [[main]]
  # identifier = "posts"
  # name = "posts"
  # url = "posts"
  # weight = 4

# [[main]]
  # identifier = "notes"
  # name = "notes"
  # url = "notes"
  # weight = 5
